v1 =  (input("Digite algo: "))
print ('É decimal? ', v1.isdecimal())
print ('É alfanumérico? ', v1.isalnum())
print ('É alfabético? ', v1.isalpha())
print ('É ascii? ', v1.isascii())
print ('É digito? ', v1.isdigit())
print ('É um identificador? ', v1.isidentifier())
print ('Está é minúsculo? ', v1.islower())
print ('É somente espaço? ', v1.isspace())
print ('É numérico? ', v1.isnumeric())